<!-- GitHub's Linguist syntax modified(https://github.com/hronro/sublime-linguist-syntax/blob/master/syntaxes/Cabal%20Config.tmLanguage) -->
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Cabal</string>
    <key>scopeName</key>
    <string>source.cabal</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>name</key>
            <string>version</string>
            <key>match</key>
            <string>(version)\W*:\W*([\d.]+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>constant.numeric</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>name</key>
            <string>cabal-keyword</string>
            <key>match</key>
            <string>(\S+):[^/]</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>name</key>
            <string>keyword.other</string>
            <key>match</key>
            <string>&amp;&amp;</string>
        </dict>
        <dict>
            <key>name</key>
            <string>cabal-keyword</string>
            <key>match</key>
            <string>([&gt;&lt;=]+)\s*([\d.]+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>constant.numeric</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>name</key>
            <string>module-type</string>
            <key>match</key>
            <string>(benchmark|common|executable|flag|source-repository|test-suite)\s+(\S+)</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>variable.function</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>name</key>
            <string>entity.name.function</string>
            <key>match</key>
            <string>library</string>
        </dict>
        <dict>
            <key>name</key>
            <string>comment</string>
            <key>match</key>
            <string>--.*\n</string>
        </dict>
    </array>
    <key>fileTypes</key>
    <array>
        <string>cabal</string>
    </array>
</dict>
</plist>